//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.Tasks = new HashSet<Task>();
            this.Projects = new HashSet<Project>();
        }
    
        public int PersonnelID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string IDCard { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
