//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Personels = new HashSet<Personel>();
        }
    
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Personel> Personels { get; set; }
    }
}
