//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDay
    {
        public int WorkDayID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
